controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

curl_search:
    path: /books/{title}
    controller: App\Controller\BookController::searchBooksByTitle

curl_search:
    path: /books/{author}
    controller: App\Controller\BookController::searchBooksByAuthor