controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

curl_search_title:
    path: /books/{title}
    controller: App\Controller\BookController::searchBooksByTitle

curl_search_author:
    path: /books?author={author}
    controller: App\Controller\BookController::searchBooksByAuthor