controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_logout:
    path: /logout
    controller: App\Controller\LogoutController::logout

book_search_by_id:
    path: /books/id={id}
    controller: App\Controller\BookController::getBookById

curl_search_title:
    path: /books/title={title}
    controller: App\Controller\BookController::getBooksByTitle

curl_search_author:
    path: /books/author={author}
    controller: App\Controller\BookController::getBooksByAuthor

curl_search_category:
    path: /books/category={category}
    controller: App\Controller\BookController::getBooksByCategory
  
books_10_newest:
    path: /books/
    controller: App\Controller\BookController::getNewestBooks

user_favorites:
    path: /my/favorites
    controller: App\Controller\UserController::displayFavorites

user_borrowed:
    path: /my/borrowed
    controller: App\Controller\UserController::displayBorrowed

register_user:
    path: /sign-up
    controller: App\Controller\RegistrationController::index

add_favorite_book:
    path: /my/favorites/{id}
    controller: App\Controller\UserController::addFavoriteBook

add_borrowed_book:
    path: /my/borrowed/{id}
    controller: App\Controller\UserController::addBorrowedBook