controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

curl_search:
    path: /books/{title}
    controller: App\Controller\BookController::searchBooksByTitle

user:
    path: /user/favortites
    controller: App\Controller\UserController::displayFavorites