controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

curl_search:
    path: /books/searchByTitle
    controller: App\Controller\BookController::searchBooksByTitle